### ISSUE TITLE
[Feature Request] signMessage with wallet

### ISSUE THREAD

**Issue by lordrio** [dscvr-one/dscvr-canvas#15]
There is already a `connectWalletAndSendTransaction` and `signAndSendTransaction`

Is it possible to get a `signMessage` with user wallet?
- mainly to check if user is the owner of said wallet for use of authorization.

**Comment by rckprtr** [comment]
Yes, it should be there as I use it quite often.

https://github.com/dscvr-one/dscvr-canvas/blob/8e4559f87ae1f294c2821a7086c8e562aaf8db40/libs/canvas-wallet-interface/src/schema/schema.ts#L138

You will need to install "@dscvr-one/canvas-wallet-adapter"

https://github.com/dscvr-one/dscvr-canvas/blob/8e4559f87ae1f294c2821a7086c8e562aaf8db40/examples/jupiter-swap/package.json#L17

**Comment by lordrio** [comment]
Nice thanks @rckprtr, I've must have missed that because I only looked at the client SDK!
